from __future__ import annotations

# English → Chinese team name mappings for all supported leagues.
TEAM_NAMES_CN: dict[str, str] = {
    # === 英超 (E0) ===
    "Arsenal": "阿仙奴",
    "Aston Villa": "阿士東維拉",
    "Bournemouth": "般尼茅夫",
    "Brentford": "賓福特",
    "Brighton": "白禮頓",
    "Brighton & Hove Albion": "白禮頓",
    "Brighton and Hove Albion": "白禮頓",
    "Burnley": "般尼",
    "Chelsea": "車路士",
    "Crystal Palace": "水晶宮",
    "Everton": "愛華頓",
    "Fulham": "富咸",
    "Ipswich": "葉士域治",
    "Ipswich Town": "葉士域治",
    "Leeds": "列斯聯",
    "Leeds United": "列斯聯",
    "Leicester": "李斯特城",
    "Leicester City": "李斯特城",
    "Liverpool": "利物浦",
    "Man City": "曼城",
    "Manchester City": "曼城",
    "Man United": "曼聯",
    "Manchester United": "曼聯",
    "Man Utd": "曼聯",
    "Newcastle": "紐卡素",
    "Newcastle United": "紐卡素",
    "Newcastle Utd": "紐卡素",
    "Nott'm Forest": "諾定咸森林",
    "Nottingham Forest": "諾定咸森林",
    "Norwich": "諾域治",
    "Norwich City": "諾域治",
    "Sheffield United": "錫菲聯",
    "Sheffield Utd": "錫菲聯",
    "Southampton": "修咸頓",
    "Tottenham": "熱刺",
    "Tottenham Hotspur": "熱刺",
    "Watford": "屈福特",
    "West Brom": "西布朗",
    "West Bromwich Albion": "西布朗",
    "West Ham": "韋斯咸",
    "West Ham United": "韋斯咸",
    "Wolves": "狼隊",
    "Wolverhampton Wanderers": "狼隊",
    # === 英冠 (E1) ===
    "Birmingham": "伯明翰",
    "Birmingham City": "伯明翰",
    "Blackburn": "布力般流浪",
    "Blackburn Rovers": "布力般流浪",
    "Blackpool": "黑池",
    "Bristol City": "布里斯托城",
    "Cardiff": "卡迪夫城",
    "Cardiff City": "卡迪夫城",
    "Coventry": "高雲地利",
    "Coventry City": "高雲地利",
    "Derby": "打比郡",
    "Derby County": "打比郡",
    "Huddersfield": "哈特斯菲爾德",
    "Huddersfield Town": "哈特斯菲爾德",
    "Hull": "侯城",
    "Hull City": "侯城",
    "Luton": "盧頓",
    "Luton Town": "盧頓",
    "Middlesbrough": "米杜士堡",
    "Millwall": "米禾爾",
    "Peterborough": "彼德堡",
    "Peterborough United": "彼德堡",
    "Plymouth": "普利茅夫",
    "Plymouth Argyle": "普利茅夫",
    "Portsmouth": "樸茨茅夫",
    "Preston": "普雷斯頓",
    "Preston North End": "普雷斯頓",
    "QPR": "昆士柏流浪",
    "Queens Park Rangers": "昆士柏流浪",
    "Reading": "雷丁",
    "Rotherham": "洛達咸",
    "Rotherham United": "洛達咸",
    "Sheffield Weds": "錫周三",
    "Sheffield Wednesday": "錫周三",
    "Stoke": "史篤城",
    "Stoke City": "史篤城",
    "Sunderland": "新特蘭",
    "Swansea": "史雲斯",
    "Swansea City": "史雲斯",
    "Wigan": "韋根",
    "Wigan Athletic": "韋根",
    # === 西甲 (SP1) ===
    "Alaves": "艾拉維斯",
    "Ath Bilbao": "畢爾包",
    "Athletic Bilbao": "畢爾包",
    "Athletic Club": "畢爾包",
    "Ath Madrid": "馬德里體育會",
    "Atletico Madrid": "馬德里體育會",
    "Atletico": "馬德里體育會",
    "Barcelona": "巴塞隆拿",
    "Betis": "貝迪斯",
    "Real Betis": "貝迪斯",
    "Celta": "切爾達",
    "Celta Vigo": "切爾達",
    "Cadiz": "卡迪斯",
    "Elche": "艾爾切",
    "Espanyol": "愛斯賓奴",
    "Getafe": "基達菲",
    "Girona": "基羅納",
    "Granada": "格拉納達",
    "Las Palmas": "拉斯彭馬斯",
    "Leganes": "雷加利斯",
    "Mallorca": "馬略卡",
    "Osasuna": "奧沙辛拿",
    "Rayo Vallecano": "華歷簡奴",
    "Real Madrid": "皇家馬德里",
    "Sociedad": "皇家蘇斯達",
    "Real Sociedad": "皇家蘇斯達",
    "Sevilla": "西維爾",
    "Valencia": "華倫西亞",
    "Valladolid": "華拉度列",
    "Villarreal": "維拉利爾",
    # === 西乙 (SP2) ===
    "Albacete": "阿爾巴塞特",
    "Almeria": "艾美利亞",
    "Eibar": "伊巴",
    "Levante": "利雲特",
    "Malaga": "馬拉加",
    "Oviedo": "奧維多",
    "Santander": "桑坦德",
    "Racing Santander": "桑坦德",
    "Sp Gijon": "希杭",
    "Sporting Gijon": "希杭",
    "Tenerife": "特內里費",
    "Zaragoza": "薩拉戈薩",

    # === 德甲 (D1) ===
    "Augsburg": "奧格斯堡",
    "Bayern Munich": "拜仁慕尼黑",
    "Bochum": "波琴",
    "Werder Bremen": "雲達不萊梅",
    "Dortmund": "多蒙特",
    "Ein Frankfurt": "法蘭克福",
    "Eintracht Frankfurt": "法蘭克福",
    "Frankfurt": "法蘭克福",
    "Freiburg": "弗賴堡",
    "Hamburg": "漢堡",
    "Heidenheim": "海登咸",
    "Hertha": "哈化柏林",
    "Hertha Berlin": "哈化柏林",
    "Hoffenheim": "賀芬咸",
    "Kiel": "基爾",
    "Holstein Kiel": "基爾",
    "FC Koln": "科隆",
    "Koln": "科隆",
    "Leverkusen": "利華古遜",
    "Mainz": "緬恩斯",
    "M'gladbach": "慕遜加柏",
    "B. Monchengladbach": "慕遜加柏",
    "RB Leipzig": "RB 萊比錫",
    "Schalke 04": "史浩克04",
    "Schalke": "史浩克04",
    "St Pauli": "聖保利",
    "Stuttgart": "史特加",
    "Union Berlin": "柏林聯",
    "Wolfsburg": "禾夫斯堡",
    # === 德乙 (D2) ===
    "Darmstadt": "達斯泰特",
    "Dusseldorf": "杜塞爾多夫",
    "Fortuna Dusseldorf": "杜塞爾多夫",
    "Hannover": "漢諾威",
    "Kaiserslautern": "凱沙羅頓",
    "Karlsruhe": "卡斯魯厄",
    "Magdeburg": "馬格德堡",
    "Nurnberg": "紐倫堡",
    "Paderborn": "柏達邦",
    "Regensburg": "雷根斯堡",
    "Braunschweig": "布倫瑞克",
    "Elversberg": "艾華斯堡",
    # === 意甲 (I1) ===
    "Atalanta": "阿特蘭大",
    "Bologna": "博洛尼亞",
    "Cagliari": "卡利亞里",
    "Como": "科木",
    "Empoli": "安玻里",
    "Fiorentina": "費倫天拿",
    "Genoa": "熱拿亞",
    "Inter": "國際米蘭",
    "Inter Milan": "國際米蘭",
    "Juventus": "祖雲達斯",
    "Lazio": "拉素",
    "Lecce": "萊切",
    "AC Milan": "AC 米蘭",
    "Milan": "AC 米蘭",
    "Monza": "蒙沙",
    "Napoli": "拿玻里",
    "Parma": "帕爾馬",
    "Roma": "羅馬",
    "Salernitana": "沙蘭力坦拿",
    "Sampdoria": "森多利亞",
    "Sassuolo": "薩斯索羅",
    "Torino": "拖連奴",
    "Udinese": "烏甸尼斯",
    "Venezia": "威尼斯",
    "Verona": "維羅納",
    # === 意乙 (I2) ===
    "Bari": "巴里",
    "Brescia": "布雷西亞",
    "Catanzaro": "卡坦沙奴",
    "Cittadella": "薛達迪拉",
    "Cosenza": "科森察",
    "Cremonese": "克雷莫納",
    "Frosinone": "費辛隆尼",
    "Modena": "摩德納",
    "Palermo": "巴勒莫",
    "Pisa": "比薩",
    "Spezia": "史柏斯亞",
    "Sudtirol": "蘇迪路",
}


def translate_team(name: str) -> str:
    """Return Chinese name if available, else original English name."""
    return TEAM_NAMES_CN.get(name.strip(), name.strip())


def translate_team_cn(name: str) -> str:
    """Return Chinese name only, or empty string if no mapping found."""
    return TEAM_NAMES_CN.get(name.strip(), "")